### PR TITLE
[RFR] Remove jQuery dependency

### PR DESCRIPTION
**Pull request by KittyGiraudel**
Hey there,

This should remove the jQuery dependency and solve #6. Be sure to test it though. :)

### CODE REVIEW

**Comment by sankalpsans** [comment]
Hey, yes. I will open up a PR once this is ready and stable! :)

**Comment by sankalpsans** [comment]
https://github.com/arbelh/HalfStyle/pull/8 Here we go.

**Comment by arbelh** [comment]
@HugoGiraudel 
Hey there,
Thanks for the contribution.
This has worked fine so far in my tests, but I will do further tests. It'd be better to add a proper DOM ready trigger to it to prevent early execution if the target elements are not loaded yet. I will release it as V3 as this is a major change and will mention you in credits!

**Comment by sankalpsans** [comment]
@arbelh Glad it works! Thanks for accepting to release it! :)

**Comment by sankalpsans** [comment]
@arbelh Hey, been a long time. Any timeline on when this is planned to be released?

**Comment by sankalpsans** [comment]
Hey @arbelh any update on this? Is there something more that is expected from this feature?

**Pull request closed without merging**
